#!/usr/bin/env bun
// Refresh ~/vault/api/PROVIDERS.md from ~/vault/api/models.json + live provider model lists.
// Run daily via cron (see SETUP.md) or manually after editing models.json.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { homedir } from "node:os";
import { join } from "node:path";

const API_DIR = join(homedir(), "vault", "api");
const REGISTRY = join(API_DIR, "models.json");
const DOC = join(API_DIR, "PROVIDERS.md");

type ModelMeta = { intel?: number | null; notes?: string };
type Provider = {
  base: string;
  pass?: string;
  auth?: "bearer" | "anthropic";
  list?: string; // model-list URL; absent = static provider (no list API)
  notes?: string;
  models: Record<string, ModelMeta>;
};
type Registry = { providers: Record<string, Provider> };

type LiveModel = { id: string; ctx?: number; status?: string };

function passShow(path: string): string {
  return execFileSync("pass", ["show", path], { encoding: "utf8" }).trim().split("\n")[0];
}

// ponytail: tolerate the common list shapes ({data:[]},{models:[]},bare []) — extend when a provider breaks it
function extractModels(json: unknown): LiveModel[] {
  const j = json as Record<string, unknown>;
  const arr = Array.isArray(json) ? json : (j?.data ?? j?.models ?? j?.items ?? []);
  if (!Array.isArray(arr)) return [];
  return arr
    .map((e: Record<string, unknown>) =>
      typeof e === "string"
        ? { id: e as string }
        : {
            id: String(e.id ?? e.name ?? e.model ?? ""),
            ctx: (e.context_length ?? e.max_model_len ?? e.context_window) as number | undefined,
            status:
              e.hot === true ? "hot" : e.hot === false ? "cold" : ((e.status ?? e.model_class) as string | undefined),
          },
    )
    .filter((e) => e.id);
}

async function fetchLive(name: string, p: Provider): Promise<{ live: Map<string, LiveModel>; line: string }> {
  if (!p.list) return { live: new Map(), line: "static (no list API)" };
  try {
    const headers: Record<string, string> = {};
    if (p.pass) {
      const key = passShow(p.pass);
      if (p.auth === "anthropic") {
        headers["x-api-key"] = key;
        headers["anthropic-version"] = "2023-06-01";
      } else headers.Authorization = `Bearer ${key}`;
    }
    const res = await fetch(p.list, { headers, signal: AbortSignal.timeout(30_000) });
    if (!res.ok) return { live: new Map(), line: `FETCH FAILED: HTTP ${res.status}` };
    const models = extractModels(await res.json());
    return { live: new Map(models.map((m) => [m.id, m])), line: `${models.length} models listed` };
  } catch (err) {
    return { live: new Map(), line: `FETCH FAILED: ${err}` };
  }
}

const reg: Registry = JSON.parse(readFileSync(REGISTRY, "utf8"));
const now = new Date().toISOString().slice(0, 16) + "Z";
const out: string[] = [
  "# API Providers — live status",
  "",
  `> GENERATED by \`arc-skills/skills/api-providers/refresh.ts\` — edit \`~/vault/api/models.json\`, never this file.`,
  `> Updated: ${now}. Key usage + routing guidance: \`/api-providers\` skill.`,
  "",
];

for (const [name, p] of Object.entries(reg.providers)) {
  const { live, line } = await fetchLive(name, p);
  out.push(`## ${name}`, "");
  out.push(`\`${p.base}\` · key \`pass show ${p.pass}\` · ${line} (${now})`);
  if (p.notes) out.push(`> ${p.notes}`);
  out.push("", "| model | avail | warm/status | ctx | intel | notes |", "|---|---|---|---|---|---|");
  for (const [id, meta] of Object.entries(p.models)) {
    const m = live.get(id);
    const avail = !p.list ? "static" : line.startsWith("FETCH FAILED") ? "?" : m ? "✓" : "✗";
    out.push(
      `| ${id} | ${avail} | ${m?.status ?? "-"} | ${m?.ctx ?? "-"} | ${meta.intel ?? "?"} | ${meta.notes ?? ""} |`,
    );
  }
  out.push("");
}

mkdirSync(API_DIR, { recursive: true });
writeFileSync(DOC, out.join("\n"));
console.log(`wrote ${DOC}`);
